# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/awerkiler/CLionProjects/hiload_nginix

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/awerkiler/CLionProjects/hiload_nginix

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/awerkiler/CLionProjects/hiload_nginix/CMakeFiles /home/awerkiler/CLionProjects/hiload_nginix//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/awerkiler/CLionProjects/hiload_nginix/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hello

# Build rule for target.
hello: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hello
.PHONY : hello

# fast build rule for target.
hello/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/build
.PHONY : hello/fast

#=============================================================================
# Target rules for targets named hiload_nginix

# Build rule for target.
hiload_nginix: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hiload_nginix
.PHONY : hiload_nginix

# fast build rule for target.
hiload_nginix/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hiload_nginix.dir/build.make CMakeFiles/hiload_nginix.dir/build
.PHONY : hiload_nginix/fast

hello.o: hello.c.o

.PHONY : hello.o

# target to build an object file
hello.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/hello.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hiload_nginix.dir/build.make CMakeFiles/hiload_nginix.dir/hello.c.o
.PHONY : hello.c.o

hello.i: hello.c.i

.PHONY : hello.i

# target to preprocess a source file
hello.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/hello.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hiload_nginix.dir/build.make CMakeFiles/hiload_nginix.dir/hello.c.i
.PHONY : hello.c.i

hello.s: hello.c.s

.PHONY : hello.s

# target to generate assembly for a file
hello.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/hello.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hiload_nginix.dir/build.make CMakeFiles/hiload_nginix.dir/hello.c.s
.PHONY : hello.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hiload_nginix.dir/build.make CMakeFiles/hiload_nginix.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hiload_nginix.dir/build.make CMakeFiles/hiload_nginix.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hiload_nginix.dir/build.make CMakeFiles/hiload_nginix.dir/main.c.s
.PHONY : main.c.s

mem_manager.o: mem_manager.c.o

.PHONY : mem_manager.o

# target to build an object file
mem_manager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hiload_nginix.dir/build.make CMakeFiles/hiload_nginix.dir/mem_manager.c.o
.PHONY : mem_manager.c.o

mem_manager.i: mem_manager.c.i

.PHONY : mem_manager.i

# target to preprocess a source file
mem_manager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hiload_nginix.dir/build.make CMakeFiles/hiload_nginix.dir/mem_manager.c.i
.PHONY : mem_manager.c.i

mem_manager.s: mem_manager.c.s

.PHONY : mem_manager.s

# target to generate assembly for a file
mem_manager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hiload_nginix.dir/build.make CMakeFiles/hiload_nginix.dir/mem_manager.c.s
.PHONY : mem_manager.c.s

queue.o: queue.c.o

.PHONY : queue.o

# target to build an object file
queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hiload_nginix.dir/build.make CMakeFiles/hiload_nginix.dir/queue.c.o
.PHONY : queue.c.o

queue.i: queue.c.i

.PHONY : queue.i

# target to preprocess a source file
queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hiload_nginix.dir/build.make CMakeFiles/hiload_nginix.dir/queue.c.i
.PHONY : queue.c.i

queue.s: queue.c.s

.PHONY : queue.s

# target to generate assembly for a file
queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hiload_nginix.dir/build.make CMakeFiles/hiload_nginix.dir/queue.c.s
.PHONY : queue.c.s

stack.o: stack.c.o

.PHONY : stack.o

# target to build an object file
stack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hiload_nginix.dir/build.make CMakeFiles/hiload_nginix.dir/stack.c.o
.PHONY : stack.c.o

stack.i: stack.c.i

.PHONY : stack.i

# target to preprocess a source file
stack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hiload_nginix.dir/build.make CMakeFiles/hiload_nginix.dir/stack.c.i
.PHONY : stack.c.i

stack.s: stack.c.s

.PHONY : stack.s

# target to generate assembly for a file
stack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hiload_nginix.dir/build.make CMakeFiles/hiload_nginix.dir/stack.c.s
.PHONY : stack.c.s

tp_pool.o: tp_pool.c.o

.PHONY : tp_pool.o

# target to build an object file
tp_pool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hiload_nginix.dir/build.make CMakeFiles/hiload_nginix.dir/tp_pool.c.o
.PHONY : tp_pool.c.o

tp_pool.i: tp_pool.c.i

.PHONY : tp_pool.i

# target to preprocess a source file
tp_pool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hiload_nginix.dir/build.make CMakeFiles/hiload_nginix.dir/tp_pool.c.i
.PHONY : tp_pool.c.i

tp_pool.s: tp_pool.c.s

.PHONY : tp_pool.s

# target to generate assembly for a file
tp_pool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hiload_nginix.dir/build.make CMakeFiles/hiload_nginix.dir/tp_pool.c.s
.PHONY : tp_pool.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hello"
	@echo "... hiload_nginix"
	@echo "... hello.o"
	@echo "... hello.i"
	@echo "... hello.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mem_manager.o"
	@echo "... mem_manager.i"
	@echo "... mem_manager.s"
	@echo "... queue.o"
	@echo "... queue.i"
	@echo "... queue.s"
	@echo "... stack.o"
	@echo "... stack.i"
	@echo "... stack.s"
	@echo "... tp_pool.o"
	@echo "... tp_pool.i"
	@echo "... tp_pool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

